---
title: "Projects"
---

## Project 1

Capstone Research Experience, Hale Lab, Durham, NH					August 2024 – Present
Agricultural Research Assistant to 2024 Innovator of the Year Professor Dr. Iago Hale

- Conducting nutritional analysis on over 200 kiwiberry progeny of trees with favorable fruit traits and trees with low oxalate with the purpose of discovering trees with both qualities
- Engaging in extensive data analysis on fruit traits and physical and nutritional qualities for the purpose of determining if a successful cross was achieved

## Project 2

Hale Lab, Woodman Horticultural Research Farm, Durham, NH					May 2024 – Present
Agricultural Research Assistant to 2024 Innovator of the Year Professor Dr. Iago Hale

- Supported the breeding and development of kiwiberry trees ensuring optimal tree health under regional conditions
- Performed consistent maintenance to promote the health and development of the populations
- Provided critical care to younger populations as they matured to ensure successful incorporation into the program
- Collected time-sensitive data on the flowering of two populations of over 200 specimens
- Harvested ripe berries for nutritional and flavor analysis, contributing to data analysis on fruit yield and quality

## Project 3

UNH Phyto Lab, UNH Marine Biology Lab, Durham, NH					Jan 2023 - August 2024
Research Assistant to Post-Doctorate Fellow Sean Anderson and Associate Professor Dr. Elizabeth Harvey

- Designed and led experiments on the uptake of 96 organic compounds by phytoplankton and parasites using Biolog plates to determine the presence of absorption of compounds or consumption of plankton
- Explored the parasitic relationship between dinospores and phytoplankton; specifically the interspecies dynamic between population numbers
- Helped design and conduct experiments and performed data analysis; conducted field sampling along the coast of NH for phytoplankton